sudo: required
services:
  - docker

before_install:
  - docker build -t jbrightstores/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jbrightstores/react-test npm test -- --coverage

after_success:
  - docker build -t jbrightstores/multi-client ./client
  - docker build -t jbrightstores/multi-server ./server
  - docker build -t jbrightstores/multi-worker ./worker
  - docker built -t jbrightstores/multi-nginx ./nginx

  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to docker hub
  - docker push jbrightstores/multi-client
  - docker push jbrightstores/multi-server
  - docker push jbrightstores/multi-worker
  - docker push jbrightstores/multi-nginx
